name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest        # 1) Use a clean Ubuntu VM
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v4    # 2) Clone YOUR repo at the pushed commit

    - name: Set up JDK
      uses: actions/setup-java@v4  # 3) Ensure Java 21 is on the PATH

    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: latest
        packages:                  # 4) Pull down exactly the SDK components you need
          - platform-tools
          - platforms;android-35
          - build-tools;35.0.0

    - name: Cache Gradle
      uses: gradle/gradle-build-action@v3
      # 5) Cache ~/.gradle between runs to speed up downloads

    - name: Assemble Debug & Run Unit Tests
      run: ./gradlew lintDebug testDebugUnitTest assembleDebug
      # 6) Run lint, unit tests, and produce a debug APK

    - name: Assemble Release artifacts
      run: ./gradlew :app:bundleRelease :app:assembleUniversalRelease
      # 7) Produce a signed AAB and a universal-release APK (unsigned by default)

    - name: Upload build outputs
      uses: actions/upload-artifact@v4
      with:
        name: secuedge-build       # 8) Make the APK/AAB downloadable
        path: |
          app/build/outputs/**/*.aab
          app/build/outputs/**/*.apk
